name: Run R Script

on:
  schedule:
    - cron: '0 20 * * *'  # Runs daily at 20:00 UTC (4 AM Taipei time)
  push:
    branches:
      - main

    paths:
      - 'R/**'

  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Install renv and restore packages
        run: |
          Rscript -e 'install.packages("renv")'
          Rscript -e 'renv::restore()'

      - name: Build map and record result
        run: Rscript R/generate_map.R
        env:
          ACCOUNT_TOKEN: ${{ secrets.ACCOUNT_TOKEN }}
